/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false worker/worker-configuration.d.ts` (hash: 55059e4fd61d01d57cd16c7a382badbd)
interface __BaseEnv_Env {
	VOYANT_ENVIRONMENT?: "staging" | "production";
	ORIGIN_TRUST_SECRET?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface StagingEnv {
		VOYANT_ENVIRONMENT: "staging";
		ORIGIN_TRUST_SECRET: string;
	}
	interface ProductionEnv {
		VOYANT_ENVIRONMENT: "production";
		ORIGIN_TRUST_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VOYANT_ENVIRONMENT" | "ORIGIN_TRUST_SECRET">> {}
}
